[tool.poetry]
name = "ai-cto"
version = "0.1.0"
description = ""
authors = ["Germuu <jeremyyamajako@gmail.com>"]
readme = "README.md"

packages = [{ include = "..src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
flask = "^3.1.0"
psycopg2-binary = "^2.9.10"
python-dotenv = "^1.0.1"
openai = "^1.59.9"
flask-sqlalchemy = "^3.1.1"
bokeh = "^3.6.2"
robotframework = "^7.2"
robotframework-seleniumlibrary = "^6.7.0"
webdrivermanager = "^0.10.0"
flask-limiter = {extras = ["sqlalchemy"], version = "^3.10.1"}
flask-caching = "^2.3.1"
pymupdf = "^1.25.3"
fitz = "^0.0.1.dev2"
webdriver-manager = "^4.0.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
